
import type { Metadata } from "next";
import { Source_Sans_3 } from "next/font/google";
import "./globals.css";
import '@fortawesome/fontawesome-svg-core/styles.css'
import { config } from '@fortawesome/fontawesome-svg-core'
import DisplayProvider from "@/context/DispayContext";
config.autoAddCss = false


const sourceFont = Source_Sans_3({
   subsets:['latin'],
   weight:"500"
   
})

export const metadata: Metadata = {
  title: "CEG Software Tools",
  description: "Generated by create next app",
};



export default function RootLayout({ children,}: Readonly<{children: React.ReactNode }>) {



   return (
      <html lang="en">
         <body
            className={` antialiased `}
         >
            
            <DisplayProvider>
                  {children}

            </DisplayProvider>
         </body>
      </html>
   );
}
